#ifndef PLANETARYORBITALECCENTRICITYTABLECONSTANTS
#define PLANETARYORBITALECCENTRICITYTABLECONSTANTS

const int ECCENTRICITYCONSTANTARRAYSIZE = 11;
const float ECCENTRICITYCONSTANTS[ECCENTRICITYCONSTANTARRAYSIZE] = {0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8};

#endif
